---
title: "R Markdown and Leaflet"

date: "22/10/2019"
#output: ioslides_presentation
---
# Africa countries by population.

This page displays Africa countries by their population in October 2019.
The source data come's from [this website].

Please select a country to for more detail.


```{r, echo=FALSE, comment=FALSE, warning=FALSE, results='hide'}
library(leaflet)
#Loading the data
#The data will be downloaded if not found in the folder
#Download the data
dataUrl <- "https://raw.githubusercontent.com/Chinasa1/DataProductsWeek2/master/CountryPopulation.csv"

fileName <- "CountryPopulation.csv"

if(!file.exists(fileName)){
  download.file(dataUrl, fileName, method = "curl")
}


#read the data
countries <- read.csv(fileName, sep=";")

#Let check the content of the data
head(countries)

#Let check the structure of the data
str(countries)

#convert the population from factor to integer
countries$Population <- as.integer(as.character(countries$Population))

#we add new variable popup message to the data
countries$popup <- apply(countries, 1 ,function(x) paste("Country: ", x[1], "<br>ISO: ",x[2],"<br>Population: ",format( as.integer(x[5]), decimal.mark=",",big.mark=" ", small.interval=3), "<br>Density: ",x[6], sep = "")) 



```
```{r, echo=FALSE, comment=FALSE, warning=FALSE}
#Display the countries with the cercle for the population
countries %>%
  leaflet() %>%
  addTiles() %>%
  addCircles(weight = 1, lng = ~lng, lat = ~lat, radius = sqrt(countries$Population) *30, popup = countries$popup)
```

[this website]: https://www.worldometers.info/population/countries-in-africa-by-population/